version: "3"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      ENVFILE_PATH: redis.env
  redis:
    image: bitnami/redis:5.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  redis-sentinel:
    image: bitnami/redis-sentinel:5.0
