apiVersion: v1
kind: Service
metadata:
  name: yocotto-url
  labels:
    app: yocotto-url
spec:
  selector:
    app: yocotto-url
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
